openapi: 3.0.0
x-stoplight:
  id: jz5lz09h0jkh2
info:
  title: Translate
  version: '1.0'
  description: Translate text between two languages
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
    url: 'http://www.leorbrenman.com'
  license:
    name: NA
    url: 'http://www.leorbrenman.com'
servers:
  - url: 'http://localhost:8080/api'
    description: localhost
paths:
  /translatetext:
    get:
      summary: Translate Text
      tags:
        - translate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/successReponse.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/errorResponse.yaml
      operationId: get-translatetext
      description: Translate text
      parameters:
        - schema:
            type: string
          in: query
          name: SourceLanguageCode
          description: 'Language code for input text (https://docs.aws.amazon.com/translate/latest/dg/what-is-languages.html)'
          required: true
        - schema:
            type: string
          in: query
          name: TargetLanguageCode
          description: 'Language code for desired translation (https://docs.aws.amazon.com/translate/latest/dg/what-is-languages.html)'
          required: true
        - schema:
            type: string
          in: query
          name: Text
          description: Text to translate
          required: true
components:
  schemas: {}
  securitySchemes:
    apiKey:
      name: API Key
      type: apiKey
      in: header
tags:
  - name: translate
    description: translate
security:
  - apiKey: []
